# Numpy(Numerical Python) : 수치 데이터, 배열(벡터, 행렬) 계산

- 공식 : https://numpy.org/
- 참고문서 : https://numpy.org/doc/
- 명령어 참고사이트 : https://ebbnflow.tistory.com/160

<img src = https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/2880px-NumPy_logo.svg.png width = 300>

- 스칼라 : 숫자 하나, 차원이 0인 값
- 벡터 : 1차원 배열
- 행렬 : 2차원 배열
- 텐서 : 3차원 이상의 배열
- numpy : 해당 위의 것들을 계싼할때 쓰임
- 파이썬과 C:
- 파이썬 : 객체지향, 느림
- numpy : 위 문제를 해결하기 위해 대규모 데이터를 C배열로 저장
- ㄴ> 겉은 파이썬 내부는 C언어
- 시퀀스 : 일정한 순서대로 나열된 것
- 벡터화 : 파이썬 루프 없이 C로 작성된 내부 루프가 한번에 처리
- 함수 / 메서드 : 
- 함수 : 모듈 전역에 놓임 / 괄호 X
- 메서드 : 어떤 객체에 붙어 해당 객체가 동작하도록 만드는 것 / 클래스에 정의, 인스턴스에서 속성 접근을 통해 호출 / 접근되는 / 함수 괄호 O
- 캡슐화 : 객체 지향 프로그래밍에서 데이터와 해당 데이터를 다루는 메소드를 하나로 묶고, 외부에서는 데이터에 직접 접근하지 못하도록 숨기는(정보 은닉) 개념
- np.random.rand(n) -> 0이상 1미만, 균일 분포 실수
- np.random.randint(low, high, size) -> 정수 난수(low에서 high중에 size 수 만큼), 균일 분포
- np.random.uniform(low, high, size) -> 실수 난수(low에서 high중에 size 수 만큼), 균일 분포
- np.random.randn(n) -> 평균 0, 표준편차 1인 정규분포 실수(마이너스 포험)
- np.random.normal(loc, scale, size) -> 평균(loc), 표준편차(scale)를 내가 임의로 지정할 수 있음
- 균일 분포 : 모든 데이터가 동등한 확률로 뽑히는 것 / ex) 주사위 1/6
- 정규(가우스, 가우시안) 분포 : 평균과 표준편차가 주어져 있을 때 엔트로피를 최대화하는 분포
- 가우시안 노이즈 : 정규 분포를 따르는 무작위 잡음 -> 학습 데이터에 오버피팅(과적합)을 방지하기 위해 사용해 잡음을 섞음 -> 모델이 완전짱쎈슈퍼모델이 됨
- ㄴ> 과적합 : 너무 한 종류의 데이터에만 집중된 거시기 무느알? 무느알? 모르면 죽어 이씌
- 디퓨전 모델 : 무작위 노이즈를 점진적으로 정제하여 이미지나 텍스트 같은 데이터를 생성하는 머신러닝의 한 종류인 생성 모델
- ㄴ> 노이즈 : 데이터(이미지·음성·텍스트 등)에 인위적으로 추가한 무작위 값으로, 원래 정보가 점점 사라지게 만드는 역할을 한다.
- 직선거리 = 유클리드 거리 : 직선과 직선 사이에 가장 짧은 거리
- ㄴ> 특성과의 유사도를 판별/측정할 때 사용
- 멘헤튼 거리 : 특성이 희소하거나 이상치에 덜 민감할 때 사용
- norm : 벡터의 길이를 재는 함수 인데 이거의 대표적인 예시가 위에 2개임
- KNN : 분류 모델로, 가장 가까운 이웃 데이터를 기준으로 판단하는 알고리즘
- K -means : 클러스터의 개수를 미리 정하여 반복적으로 클러스터의 평균을 업데이트하며 가장 가까운 점들을 군집화하는 방법 / 이상치 검출 불가
- DBSCAN : 유클리드 거리 사용 X / 말도에 따라 군집화
- 연산자 오버로딩 : 연산자의 기능을 재정의
- 행렬의 내적 : 나올수 있는 경우의 수를 한번에 모두 구하는 것
- 지도 : 분류 / KNN / SVM
- 비지도 : K-means / 
- 강화 : 
- Noise point : epsilon내에 점이 1개도 없을 떄
- 역행렬 A = (a b)(c d) | 1/ad-bc(d -b)(-c a) | ad - bc = 행렬식(determinent)
- 행렬식이 0이 되면 역행렬이 생성되지 않음
- 선형대수에서 행렬은 함수와 같은 역할을 수행, 함수 대신 변환이라는 용어 사용
- 행렬식이 0이면 차원이 줄어듬, 역행렬 존재 x | 사용 예시 : 병원 MRI, 교통 흐름 시뮬레이션, 불이 나고 난 후 산의 면적


### 1️⃣ 리스트와 다른 점 (1-10번)

> NumPy 배열이 Python 리스트와 어떻게 다르고, 왜 더 강력한지 이해해 봅시다.

**1. 결과 예측하기**
다음 코드의 실행 결과는 무엇일까요?

In [10]:
my_list = [1, 2, 3]
#my_list.
print(my_list * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


**2. 결과 예측하기**
이번엔 NumPy 배열입니다. 위 코드와 비교했을 때 실행 결과는 어떻게 다를까요?

In [11]:
import numpy as np
my_arr = np.array([1, 2, 3])
print(my_arr * 3)

[3 6 9]


**3. 개념 이해하기**
Python 리스트는 서로 다른 자료형(예: 정수, 문자열)을 함께 저장할 수 있습니다. NumPy 배열도 그럴까요? 그 이유를 **'동종(homogeneous)'** 이라는 키워드를 사용해 설명해 보세요.


정답:numpy는 동종 데이터타입만 저장할 수 있고 연속된 메모리 공간에 저장해서 연산속도를 노피무
서로 다른 타입의 데이터타입이 섞여있으면 자동으로 모두 동일하게 형변환

In [12]:
A = [1, 'hello', 3.14, 2+3j]
print(A)

[1, 'hello', 3.14, (2+3j)]


In [13]:
import numpy as np
A = np.array([1, 'hello', 3.14, 2+3j])
print(A)

['1' 'hello' '3.14' '(2+3j)']



**4. 결과 예측하기**
두 리스트를 더하면 어떤 결과가 나올까요?

In [14]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1 + list2)

[1, 2, 3, 4, 5, 6]


**5. 결과 예측하기**
NumPy 배열로 똑같이 덧셈을 하면 어떻게 될까요? 이 연산을 무엇이라고 부를까요?

In [15]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)

[5 7 9]


**6. 코드 완성하기**
리스트 `[0, 1, 2, 3, 4]`를 사용하여 NumPy 배열 `arr`을 생성하는 코드를 완성하세요.

In [16]:
import numpy as np
my_list = [0, 1, 2, 3, 4]
arr = np.array(my_list)
print(arr)

[0 1 2 3 4]


정답:array

**7. 개념 비교하기**
아주 큰 숫자 리스트의 모든 값에 2를 곱하는 작업과, 동일한 크기의 NumPy 배열에 2를 곱하는 작업 중 어느 것이 더 빠를까요? 그 이유는 무엇일까요? (힌트: 내부 구현, 벡터화)



정답:numpy는 내부적으로 c언어로 구현되있어 연산속도가 매우 빠름

**8. 코드 완성하기**
`arr`가 NumPy 배열일 때, 배열에 저장된 값들의 데이터 타입을 확인하는 코드를 빈칸에 채워 넣으세요.

In [22]:
import numpy as np
arr = np.array([1.0, 2.5, 3.3])
print(arr.dtype)

float64


정답:dtype

**9. 결과 예측하기**
다음 코드의 실행 결과는 무엇일까요?

In [21]:
import numpy as np
arr = np.array([1, 2, 'lwiehbviwejkwebv;erwjhlvjeqjavhakelscmpoehvnlvhelqiuwnclowehfnkjwesjkciowehfiuwejviuervijewcilukwe,sjvhlcie,kr.ufhjioeq.lrkhgbv,kdjrufjvo;ilqewnrajksvheahrsngfihweirufvnlkserhvilueshrvuisdkghkejsrhvdilrshvkejrsdhfglhweliurk,jdgvhlowerhfvlkj nweiorhfiukvcwnelrisugyhiulqwbfvcdshvliqwubgfvlieahvcliquebvaelhbvbilaerkjncq   ofqwkjvbneriulvhbeqlrhjfhqw4ilufghvblkadfjh;9ohqgvlkjaehriubqewalvkiehrauylqbwlgfvo.ujdhafilukvbawekjfhqeiul .owhfiluaerhvncla ck,ewfgjvialbcaelkrhgliuerajkfjoaerp8hfbejkr'])
print(arr.dtype)

<U492


NumPy 배열은 동종 데이터를 유지해야 하므로, 숫자와 문자열이 섞이면 더 넓은 범위인 문자열 타입으로 통일됩니다.

*(힌트: NumPy 배열은 동종 데이터를 저장합니다.)*

**10. 개념 이해하기**
메모리 효율성 측면에서 리스트와 NumPy 배열 중 어느 것이 더 우수할까요? 그 이유를 간단히 설명하세요.

-----



정답:numpy

### 2️⃣ NumPy의 다양한 메소드 활용 (11-30번)

> 배열을 만들고, 모양을 바꾸고, 원하는 데이터만 쏙쏙 뽑아내는 방법을 배워봅시다.

**11. 코드 완성하기**
0부터 9까지의 정수를 가진 배열을 만드는 가장 효율적인 방법입니다. 빈칸을 채우세요.

In [27]:
import numpy as np
arr = np.arange(0, 4, 0.2)
print(arr)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8]


정답:arange

**12. 코드 완성하기**
모든 값이 1로 채워진 3x4 크기(3행 4열)의 2차원 배열을 만드세요.

In [30]:
import numpy as np
arr = np.zeros( (3, 4) )
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


정답:

**13. 결과 예측하기**
아래 코드의 출력 결과는 무엇일까요?

In [24]:
import numpy as np
arr = np.arange(12)
print(arr.reshape(4, 3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


shape : 배열의 구조를 알려주는 것

**14. 결과 예측하기**
배열 `arr`의 \*\*차원(dimension)\*\*과 \*\*모양(shape)\*\*을 출력하는 코드입니다. 결과는?

In [31]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.ndim)
print(arr.shape)

2
(3, 2)


**15. 코드 완성하기 (인덱싱)**
2차원 배열 `arr`에서 값 `8`을 출력하려고 합니다. 올바른 인덱스를 넣으세요.

In [33]:
import numpy as np
arr = np.arange(9).reshape(3, 3)
# [[0, 1, 2],
#  [3, 4, 5],
#  [6, 7, 8]]
print(arr[2 , 2])

8


정답:2, 2

**16. 결과 예측하기 (슬라이싱)**
다음 코드의 실행 결과는 무엇일까요?

In [34]:
import numpy as np
arr = np.arange(10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(arr[2:5])

[2 3 4]


**17. 결과 예측하기 (슬라이싱)**
다음 코드의 실행 결과는 무엇일까요?

In [37]:
import numpy as np
arr = np.arange(15).reshape(3, 5)
print(arr[1, :])

[5 6 7 8 9]


**18. 코드 완성하기 (Boolean 인덱싱)**
배열 `arr`에서 5보다 큰 값들만 추출하는 코드를 완성하세요.

In [40]:
import numpy as np
arr = np.array([1, 8, 3, 6, 2, 7])
bool_mask = arr > 5
print(bool_mask)

[False  True False  True False  True]


정답: 불리언 마스킹이란 조건에 따라 특정 값을 부여하는 작업을 의미

**19. 결과 예측하기 (Fancy 인덱싱)**
다음 코드의 실행 결과는 무엇일까요?

In [38]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
indices = [[0, 1], [1, 2]]
print(arr[indices])

[[10 20]
 [20 30]]


**20. 코드 완성하기**
1차원 배열 `arr`을 2x5 형태의 2차원 배열 `arr_2d`로 바꾸세요.

In [41]:
import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape( (2, 5) )
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


정답:

**21. 결과 예측하기**
`arr.T`는 무엇을 하는 코드일까요? 실행 결과를 예측해 보세요.

In [42]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(arr.T)

[[1 3]
 [2 4]]


- 행은 데이터의 건수
- 열은 데이터의 특성

**22. 코드 완성하기**
두 배열 `a`와 `b`를 수평으로(옆으로) 합치는 코드를 완성하세요.

In [44]:
import numpy as np
a = np.array([1, 2])
b = np.array([3, 4])
c = np.hstack( (a, b) )
d = np.vstack( (a, b) )
print(c)
print(d)

[1 2 3 4]
[[1 2]
 [3 4]]


정답:

**23. 코드 완성하기**
0과 1 사이의 균일한 분포에서 5개의 무작위 숫자를 생성하는 코드입니다.

In [ ]:
import numpy as np
random_arr = np.random.______(5)
print(random_arr)

정답:

**24. 결과 예측하기**
`axis=0`은 어떤 방향으로 합계를 구하는 걸까요? 결과를 예측해 보세요.

In [46]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.sum(axis=1))

[ 6 15]


0 은 행끼리
1 은 열끼리

**25. 결과 예측하기**
그렇다면 `axis=1`은 어떤 방향일까요?

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.mean(axis=1))

**26. 코드 완성하기**
배열의 모든 원소에 대한 제곱근을 구하는 유니버설 함수(ufunc)를 사용하세요.

In [ ]:
import numpy as np
arr = np.array([1, 4, 9, 16])
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)

정답:sqrt(제곱근)

**27. 결과 예측하기 (브로드캐스팅)**
크기가 다른 배열 간의 연산입니다. 어떤 결과가 나올까요?

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print(arr + b)

브로드 캐스팅 : 연산 시 배열의 크기가 다르면 자동으로 맞춰주는 방식

**28. 코드 완성하기**
배열 `arr`을 정렬하는 메소드를 사용하세요.

In [ ]:
import numpy as np
arr = np.array([3, 1, 4, 1, 5, 9, 2])
arr.sort()
print(arr)

arr.sort() - 원본 변경
np.sort(arr) - 원본 유지

정답:

**29. 결과 예측하기**
배열 `arr`에서 중복된 값을 제거하고 유일한 값만 남기면 어떤 결과가 나올까요?

In [ ]:
import numpy as np
arr = np.array([1, 2, 2, 3, 3, 3, 4])
print(np.unique(arr))

**30. 코드 완성하기**
5보다 큰 값은 1로, 아니면 0으로 바꾸는 코드를 완성하세요.

In [ ]:
import numpy as np
arr = np.arange(10)
new_arr = np.where(arr > 5, 1, 0)
print(new_arr)

정답:

-----

### 3️⃣ 수학적 응용 (31-40번)

> NumPy를 이용해 복잡한 수학 계산, 특히 선형대수를 얼마나 쉽게 해결할 수 있는지 알아봅시다.

**31. 결과 예측하기 (벡터 내적)**
두 벡터의 내적(dot product) 결과는 무엇일까요?

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))

- 내적 : 곱의 합
- ㄴ> 인공지능에서 가장 중요한 그것
- 순전파, 역전파

**32. 코드 완성하기 (행렬 곱셈)**
행렬 `A`와 `B`의 곱셈을 구해보세요

In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A __ B
print(C)

정답:

**33. 개념 이해하기**
다음 연립방정식을 NumPy로 어떻게 표현하고 풀 수 있을까요?  

$2x + y = 4$  

$x + 3y = 7$

항등원 : 항상 참

단위 행렬 = (1 0)
          (0 1)   

정답: (2 1)(1 3)  (x)(y)  =   (4)(7)  

**34. 코드 완성하기 (연립방정식 풀이)**
위 33번 문제의 연립방정식을 푸는 코드입니다. 빈칸을 채워 해를 구하세요.

In [ ]:
import numpy as np
A = np.array([[2, 1], [1, 3]])
b = np.array([4, 7])
x = np.linalg.______(A, b) # solve
print(x) # [x, y]

답:

**35. 코드 완성하기 (역행렬)**
행렬 `A`의 역행렬을 구하는 코드를 완성하세요.

In [ ]:
import numpy as np
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.______(A)
print(A_inv)

정답:

**36. 결과 예측하기**
행렬 `A`와 그 역행렬 `A_inv`를 곱하면 어떤 결과가 나올까요? (이론적으로)



정답:

**37. 코드 완성하기 (통계)**
배열 `data`의 \*\*평균(mean)\*\*과 \*\*표준편차(standard deviation)\*\*를 계산하는 코드를 완성하세요.

In [ ]:
import numpy as np
data = np.array([10, 12, 15, 11, 13])
mean_val = np.______(data)
std_val = np.______(data)
print(f"평균: {mean_val}, 표준편차: {std_val}")

정답:

**38. 결과 예측하기**
`np.linspace(0, 10, 5)`는 어떤 배열을 생성할까요?



정답:

**39. 코드 완성하기 (난수)**
평균이 0이고 표준편차가 1인 정규분포(가우시안 분포)에서 무작위 샘플 3개를 뽑는 코드입니다.

In [ ]:
import numpy as np
samples = np.random.______(3)
print(samples)

정답:

**40. 개념 이해하기**
행렬식(determinant)은 행렬의 어떤 기하학적 특징과 관련이 있을까요? `np.linalg.det()` 함수는 무엇을 계산하는 함수일까요?

행렬 : 선형 변환이 공간을 얼마나 확대, 축소 하느냐.

정답:

-----

### 4️⃣ 인공지능에서의 활용 (41-50번)

> 인공지능 모델의 데이터는 대부분 NumPy 배열입니다. 어떻게 활용되는지 맛봅시다. 🤖

**41. 개념 이해하기**
28x28 픽셀 크기의 흑백 이미지가 있다고 상상해 보세요. 이 이미지를 NumPy 배열로 어떻게 표현할 수 있을까요? (배열의 `shape`와 값의 범위)


정답:


**42. 코드 완성하기**
위 41번의 28x28 이미지 데이터를 인공지능 모델에 입력하기 위해 784개의 원소를 가진 1차원 벡터로 만드는(펼치는) 코드입니다.

In [ ]:
import numpy as np
image = np.random.rand(28, 28) # 가상의 28x28 이미지
vector = image.______()
print(vector.shape)

정답:

**43. 코드 완성하기 (활성화 함수)**
인공신경망의 대표적인 활성화 함수인 \*\*시그모이드(Sigmoid)\*\*를 NumPy로 구현하는 코드입니다.
$$\sigma(x) = \frac{1}{1 + e^{-x}}$$

In [ ]:
import numpy as np
def sigmoid(x):
  return 1 / (1 + np.____(-x))
z = np.array([-1.0, 1.0, 2.0])
print(sigmoid(z))

정답:

**44. 코드 완성하기 (활성화 함수)**
최근 가장 많이 사용되는 활성화 함수인 **ReLU**를 구현해 보세요. (0보다 작으면 0, 아니면 그 값 그대로)

In [ ]:
import numpy as np
def relu(x):
  return np.______(0, x)
z = np.array([-1.0, 0.5, -2.0, 3.0])
print(relu(z))

정답:

**45. 개념 이해하기**
인공지능 모델이 예측한 값 `y_pred`와 실제 값 `y_true`가 있을 때, \*\*평균 제곱 오차(Mean Squared Error, MSE)\*\*를 계산하는 것은 모델의 성능을 평가하는 방법 중 하나입니다. MSE를 NumPy 연산으로 어떻게 표현할 수 있을까요?



정답:

**46. 코드 완성하기 (손실 함수)**
위 45번의 MSE를 계산하는 코드입니다. 빈칸을 채워보세요.

In [ ]:
import numpy as np
y_true = np.array([1, 2, 3, 4])
y_pred = np.array([1.1, 2.3, 2.8, 4.1])
mse = np.______( (y_true - y_pred)**2 )
print(f"MSE: {mse}")

정답:

**47. 결과 예측하기 (뉴런 계산)**
인공신경망의 한 뉴런은 입력(inputs)과 가중치(weights)의 내적(dot product)으로 계산됩니다. 결과는 무엇일까요?

In [ ]:
import numpy as np
inputs = np.array([0.5, 0.3, 0.2])
weights = np.array([0.4, 0.7, 0.1])
output = np.dot(inputs, weights)
print(output)

**48. 개념 이해하기 (KNN)**
KNN(K-최근접 이웃) 알고리즘에서는 데이터 포인트 간의 거리를 계산해야 합니다. 두 데이터 포인트 `p1 = (x1, y1)`과 `p2 = (x2, y2)`가 NumPy 벡터 `v1`, `v2`로 표현될 때, 두 벡터 사이의 유클리드 거리를 NumPy로 어떻게 계산할 수 있을까요?
$$\sqrt{(x1-x2)^2 + (y1-y2)^2}$$



답:

**49. 코드 완성하기 (거리 계산)**
위 48번의 유클리드 거리를 계산하는 코드입니다.

In [ ]:
import numpy as np
v1 = np.array([1, 2])
v2 = np.array([4, 6])
distance = np.sqrt(np.____( (v1 - v2)**2 ))
print(distance)

정답:

**50. 코드 완성하기 (원-핫 인코딩)**
3개의 클래스(0, 1, 2)가 있고, 현재 데이터가 클래스 '1'이라고 할 때, 이를 `[0, 1, 0]`과 같이 표현하는 것을 원-핫 인코딩이라고 합니다. NumPy로 간단하게 구현하는 코드입니다.

In [ ]:
import numpy as np
num_classes = 3
label = 1
one_hot = np.____(num_classes)
one_hot[label] = 1
print(one_hot)

정답: